# Generated by Django 2.0.2 on 2018-02-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='buy',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=15)),
                ('uname', models.CharField(max_length=15)),
                ('pid', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=15)),
                ('qty', models.IntegerField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('mno', models.BigIntegerField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=15)),
                ('pid', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('qty', models.IntegerField(max_length=15)),
                ('image', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('cid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pid', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('pid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('dsc', models.CharField(max_length=15)),
                ('cid', models.CharField(max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='wishlist',
            fields=[
                ('wid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=15)),
                ('pid', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('image', models.CharField(max_length=15)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='mno',
            field=models.BigIntegerField(max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
