# Generated by Django 2.0.1 on 2018-04-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0004_auto_20180318_1745'),
    ]

    operations = [
        migrations.DeleteModel(
            name='buy',
        ),
    ]
