# Generated by Django 2.0.1 on 2018-04-05 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0005_delete_buy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy',
            fields=[
                ('bid', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=15)),
                ('uname', models.CharField(max_length=15)),
                ('pid', models.CharField(max_length=15)),
                ('pname', models.CharField(max_length=15)),
                ('qty', models.IntegerField(max_length=15)),
                ('price', models.IntegerField(max_length=15)),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('mno', models.BigIntegerField(max_length=15)),
                ('address', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
            ],
        ),
    ]
