# Generated by Django 2.0.1 on 2018-04-05 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0007_auto_20180406_0155'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
