# Generated by Django 2.2 on 2019-04-07 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingapp', '0008_delete_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='nadiad', max_length=200),
            preserve_default=False,
        ),
    ]
